[tool.poetry]
name = "firebase-sub"
version = "0.1.0"
description = ""
authors = ["Chris Hopkins <cbehopkins@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
firebase-admin = "^6.3.0"
mailtrap = "2.0.1"
black = "^25.1.0"
click = "^8.2.1"
isort = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
